config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'page_posts#index'

  resources :page_posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page_post.rb
class PagePost < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :page_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/page_posts_controller.rb
class PagePostsController < ApplicationController
  before_action :set_page_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /page_posts
  # GET /page_posts.json
  def index
    @page_posts = PagePost.all
  end

  # GET /page_posts/1
  # GET /page_posts/1.json
  def show
  end

  # GET /page_posts/new
  def new
    @page_post = PagePost.new
  end

  # GET /page_posts/1/edit
  def edit
  end

  # POST /page_posts
  # POST /page_posts.json
  def create
    @page_post = PagePost.new(page_post_params)

    @page_post.user_id = current_user.id
    respond_to do |format|
      if @page_post.save
        format.html { redirect_to @page_post, notice: 'Page post was successfully created.' }
        format.json { render :show, status: :created, location: @page_post }
      else
        format.html { render :new }
        format.json { render json: @page_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /page_posts/1
  # PATCH/PUT /page_posts/1.json
  def update
    respond_to do |format|
      if @page_post.update(page_post_params)
        format.html { redirect_to @page_post, notice: 'Page post was successfully updated.' }
        format.json { render :show, status: :ok, location: @page_post }
      else
        format.html { render :edit }
        format.json { render json: @page_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /page_posts/1
  # DELETE /page_posts/1.json
  def destroy
    @page_post.destroy
    respond_to do |format|
      format.html { redirect_to page_posts_url, notice: 'Page post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_page_post
    @page_post = PagePost.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def page_post_params
    params.require(:page_post).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_posts_helper.rb
module PagePostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/page_posts/_form.html.erb
<%= form_for @page_post, local: true, html: {multipart: true} do |form| %>
  <% if @page_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page_post.errors.count, t('common.errors')) %>:</h2>
      <ul>
        <% @page_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/page_posts/edit.html.erb
<h1><%= t('page_posts.edit.posts') %></h1>

<%= render 'form', page_post: @page_post %>

<%= link_to t('page_posts.edit.show'), @page_post %> |
<%= link_to t('page_posts.edit.back'), page_posts_path %>

app/views/page_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('page_posts.index.posts') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('page_posts.index.title') %></th>
      <th><%= t('page_posts.index.body') %></th>
      <th><%= t('page_posts.index.email') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @page_posts.each do |page_post| %>
      <tr>
        <td><%= page_post.title %></td>
        <td><%= page_post.body %></td>
        <td><%= page_post.user.email %></td>
        <td><%= link_to t('page_posts.index.show'), page_post %></td>
        <td><%= link_to t('page_posts.index.edit'), edit_page_post_path(page_post) %></td>
        <td><%= link_to t('page_posts.index.destroy'), page_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('page_posts.index.new_post'), new_page_post_path %>

app/views/page_posts/new.html.erb
<h1><%= t('page_posts.new.title') %></h1>

<%= render 'form', page_post: @page_post %>

<%= link_to t('page_posts.new.back'), page_posts_path %>

app/views/page_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('page_posts.show.title') %>:</strong>
  <%= @page_post.title %>
</p>

<p>
  <strong><%= t('page_posts.show.body') %>:</strong>
  <%= @page_post.body %>
  <%= image_tag @page_post.image.url(:large), class: 'img-smow' if @page_post.image? %>
</p>

<p>
  <strong><%= t('page_posts.show.email') %>:</strong>
  <%= @page_post.user.email %>
</p>

<%= link_to t('page_posts.show.edit'), edit_page_post_path(@page_post) %> |
<%= link_to t('page_posts.show.back'), page_posts_path %>